/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type RelationshipResponseStatus = typeof RelationshipResponseStatus[keyof typeof RelationshipResponseStatus];


export const RelationshipResponseStatus = {
    MARRIED: 'MARRIED',
    PARTNERED: 'PARTNERED',
    SEPARATED: 'SEPARATED',
    DIVORCED: 'DIVORCED',
    WIDOWED: 'WIDOWED',
} as const;
