/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type RelationshipResponseType = typeof RelationshipResponseType[keyof typeof RelationshipResponseType];


export const RelationshipResponseType = {
    PARENT_OF: 'PARENT_OF',
    SPOUSE_OF: 'SPOUSE_OF',
    PARTNER_OF: 'PARTNER_OF',
} as const;
